name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set env variables
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "PRERELEASE=$(mvn help:evaluate -Dexpression=prerelease -q -DforceStdout)" >> $GITHUB_ENV
          echo "EXECUTE=$(mvn help:evaluate -Dexpression=execute -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view "v${{ env.VERSION }}" > /dev/null 2>&1; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Stop if release exists
        if: env.RELEASE_EXISTS == 'true'
        run: echo "Release v${{ env.VERSION }} already exists. Stopping workflow."

      - name: Run Maven package
        if: ${{ env.EXECUTE == 'true' && env.RELEASE_EXISTS == 'false' }}
        run: mvn clean package

      - name: Get previous release tag
        id: get_prev_release
        run: echo "PREV_RELEASE=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

      - name: Get commit messages
        id: get_commits
        run: echo "COMMITS=$(git log ${{ env.PREV_RELEASE }}..HEAD --pretty=format:'%h - %s')" >> $GITHUB_ENV

      - name: Create prerelease
        if: ${{ env.EXECUTE == 'true' && env.PRERELEASE == 'true' && env.RELEASE_EXISTS == 'false' }}
        uses: ncipollo/release-action@v1
        id: preRelease
        with:
          name: "v${{ env.VERSION }}"
          artifacts: "target/output/*.jar"
          commit: ${{ github.sha }}
          tag: "${{ env.VERSION }}-${{ github.sha }}"
          draft: false
          prerelease: true
          body: |
            This release is automatically generated from commit ${{ github.sha }} and corresponds to version ${{ env.VERSION }} from pom.xml.
            Changelog for this version: ${{ github.event.head_commit.message }}
            !! THIS IS A PRERELEASE AND NOT FINAL !!

      - name: Create release final
        if: ${{ env.EXECUTE == 'true' && env.PRERELEASE == 'false' && env.RELEASE_EXISTS == 'false' }}
        uses: ncipollo/release-action@v1
        id: finalRelease
        with:
          name: "v${{ env.VERSION }}"
          artifacts: "target/output/*.jar"
          commit: ${{ github.sha }}
          tag: ${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            This release is automatically generated from commit ${{ github.sha }} and corresponds to version ${{ env.VERSION }} from pom.xml.
            Changelog for this version:
            ${{ env.COMMITS }}